[package]
name = "rftp"
version = "0.0.2"
authors = [ "realatffour <ayhamaboualfadl@gmail.com>" ]

[dependencies]
clap = "2.33.0"
regex = "1.3.1"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.41"
